[package]
name = "notify"
version = "0.1.0"
edition = "2024"

[dependencies]
lettre = "0.11.17"
reqwest = "0.12.20"
serde_json = "1.0.140"
tokio = { version = "1.45.1", features = ["full"] }
toml = "0.8.23"
