version: "3.9"

services:
    postgres:
      image: postgres:17-alpine
      environment:
        POSTGRES_PASSWORD: ${DB_PASSWD} 
        POSTGRES_USER: ${DB_USER}
        POSTGRES_DB: ${DB_NAME}
      ports:
        - 5432:5432
